library(xgboost)
library(stringi)

xyac_model_select <- function(pbp) {
  pbp %>%
    dplyr::select(
      "air_yards", "yardline_100", "ydstogo", "distance_to_goal",
      "down1", "down2", "down3", "down4", "air_is_zero", "pass_middle",
      "era2", "era3", "era4", "qb_hit", "home",
      "outdoors", "retractable", "dome", "distance_to_sticks"
    )
}

# These columns are being generated by add_xyac and the function tries to drop
# them in case it is being used on a pbp dataset where the columns already exist
drop.cols.xyac <- c(
  "xyac_epa", "xyac_mean_yardage", "xyac_median_yardage", "xyac_success", "xyac_fd"
)

made_model_mutations <- function(pbp) {
  
  pbp <- pbp %>%
    dplyr::mutate(
      #for EP, CP, and WP model, xgb needs 0/1 for eras
      era0 = dplyr::if_else(.data$season <= 2001, 1, 0),
      era1 = dplyr::if_else(.data$season > 2001 & .data$season <= 2005, 1, 0),
      era2 = dplyr::if_else(.data$season > 2005 & .data$season <= 2013, 1, 0),
      era3 = dplyr::if_else(.data$season > 2013 & .data$season <= 2017, 1, 0),
      era4 = dplyr::if_else(.data$season > 2017, 1, 0),
      #for fg model, an era factor
      era = dplyr::case_when(
        .data$era0 == 1 ~ 0,
        .data$era1 == 1 ~ 1,
        .data$era2 == 1 ~ 2,
        .data$era3 == 1 | era4 == 1 ~ 3
      ),
      era = as.factor(.data$era),
      down1 = dplyr::if_else(.data$down == 1, 1, 0),
      down2 = dplyr::if_else(.data$down == 2, 1, 0),
      down3 = dplyr::if_else(.data$down == 3, 1, 0),
      down4 = dplyr::if_else(.data$down == 4, 1, 0),
      home = dplyr::if_else(.data$posteam == .data$home_team, 1, 0),
      model_roof = dplyr::if_else(is.na(.data$roof) | .data$roof == 'open' | .data$roof == 'closed', as.character('retractable'), as.character(.data$roof)),
      model_roof = as.factor(.data$model_roof),
      retractable = dplyr::if_else(.data$model_roof == 'retractable', 1, 0),
      dome = dplyr::if_else(.data$model_roof == 'dome', 1, 0),
      outdoors = dplyr::if_else(.data$model_roof == 'outdoors', 1, 0)
    )
  
  return(pbp)
}


prepare_xyac_data <- function(pbp) {
  
  # valid pass play: at least -15 air yards, less than 70 air yards, has intended receiver, has pass location
  passes <- pbp %>%
    made_model_mutations() %>%
    dplyr::mutate(
      # receiver_player_name =
      #   stringr::str_extract(desc, glue::glue('{receiver_finder}{big_parser}')),
      pass_middle = dplyr::if_else(pass_location == "middle", 1, 0),
      air_is_zero = dplyr::if_else(air_yards == 0, 1, 0),
      distance_to_sticks = air_yards - ydstogo,
      distance_to_goal = yardline_100 - air_yards,
      valid_pass = dplyr::if_else(
        (complete_pass == 1 | incomplete_pass == 1 | interception == 1) &
          !is.na(air_yards) & air_yards >= -15 & air_yards < 70 &
          !is.na(receiver_player_name) & !is.na(pass_location),
        1, 0
      )
    )
  return(passes)
}




add_xyac <- function(pbp, ...) {
  if (nrow(pbp) == 0) {
    # user_message("Nothing to do. Return passed data frame.", "info")
  } else {
    # testing only
    # pbp <- g
    
    # pbp <- pbp %>% dplyr::select(-tidyselect::any_of(drop.cols.xyac))
    
    # for joining at the end
    pbp <- pbp %>%
      dplyr::mutate(index = 1:dplyr::n())
    
    # prepare_xyac_data helper function shown below
    passes <- prepare_xyac_data(pbp) %>%
      dplyr::filter(valid_pass == 1, distance_to_goal != 0)
    
    if (!nrow(passes) == 0) {
      # user_message("Computing xyac...", "todo")
      join_data <- passes %>%
        dplyr::select(
          "index", "distance_to_goal", "season", "week", "home_team", "posteam", "roof",
          "half_seconds_remaining", "down", "ydstogo",
          "posteam_timeouts_remaining", "defteam_timeouts_remaining",
          "original_spot" = "yardline_100", "original_ep" = "ep", "air_epa", "air_yards"
        ) %>%
        dplyr::mutate(
          down = as.integer(down),
          ydstogo = as.integer(ydstogo),
          original_ydstogo = ydstogo
        ) %>%
        dplyr::select("index":"ydstogo", "original_ydstogo", dplyr::everything())
      
      xyac_vars <-
        stats::predict(
          fastrmodels::xyac_model,
          as.matrix(passes %>% xyac_model_select())
        ) %>%
        tibble::as_tibble() %>%
        dplyr::rename(prob = "value") %>%
        dplyr::bind_cols(
          tibble::tibble(
            "yac" = rep_len(-5:70, length.out = nrow(passes) * 76),
            "index" = rep(passes$index, times = rep_len(76, length.out = nrow(passes)))
          ) %>%
            dplyr::left_join(join_data, by = "index") %>%
            dplyr::mutate(
              half_seconds_remaining = dplyr::if_else(
                half_seconds_remaining <= 6,
                0,
                half_seconds_remaining - 6
              )
            )
        ) %>%
        dplyr::group_by(index) %>%
        dplyr::mutate(
          max_loss = dplyr::if_else(distance_to_goal < 95, -5, distance_to_goal - 99),
          max_gain = dplyr::if_else(distance_to_goal > 70, 70, distance_to_goal),
          cum_prob = cumsum(prob),
          prob = dplyr::case_when(
            # truncate probs at loss greater than max loss
            yac == max_loss ~ cum_prob,
            # same for gains bigger than possible
            yac == max_gain ~ 1 - dplyr::lag(cum_prob, 1),
            TRUE ~ prob
          ),
          # get updated end result for each possibility
          yardline_100 = distance_to_goal - yac
        ) %>%
        # dplyr::filter(yac >= max_loss, yac <= max_gain) %>%
        # dplyr::select(-cum_prob) %>%
        dplyr::mutate(
          posteam_timeouts_pre = posteam_timeouts_remaining,
          defeam_timeouts_pre = defteam_timeouts_remaining,
          gain = original_spot - yardline_100,
          turnover = dplyr::if_else(down == 4 & gain < ydstogo, as.integer(1), as.integer(0)),
          down = dplyr::if_else(gain >= ydstogo, 1, down + 1),
          ydstogo = dplyr::if_else(gain >= ydstogo, 10, ydstogo - gain),
          # possession change if 4th down failed
          down = dplyr::if_else(turnover == 1, as.integer(1), as.integer(down)),
          ydstogo = dplyr::if_else(turnover == 1, as.integer(10), as.integer(ydstogo)),
          # save yardline_100 for yards gained calculation
          yardline_100_noflip = yardline_100,
          # flip yardline_100 and timeouts for turnovers for EP calculation
          yardline_100 = dplyr::if_else(turnover == 1, as.integer(100 - yardline_100), as.integer(yardline_100)),
          posteam_timeouts_remaining = dplyr::if_else(
            turnover == 1,
            defeam_timeouts_pre,
            posteam_timeouts_pre
          ),
          defteam_timeouts_remaining = dplyr::if_else(
            turnover == 1,
            posteam_timeouts_pre,
            defeam_timeouts_pre
          ),
          # ydstogo can't be bigger than yardline
          ydstogo = dplyr::if_else(ydstogo >= yardline_100, as.integer(yardline_100), as.integer(ydstogo))
        )
      
      
      pbp <- pbp %>%
        dplyr::left_join(xyac_vars, by = "index") %>%
        dplyr::select(-index)
      
      # message_completed("added xyac variables", ...)
    } else { # means no valid pass plays in the pbp
      pbp <- pbp %>%
        dplyr::mutate(
          xyac_epa = NA_real_,
          xyac_mean_yardage = NA_real_,
          xyac_median_yardage = NA_real_,
          xyac_success = NA_real_,
          xyac_fd = NA_real_
        ) %>%
        dplyr::select(-index)
      # user_message("No non-NA values for xyac calculation detected. xyac variables set to NA", "info")
    }
  }
  
  return(pbp)
}

get_ngs_pbp <- function(old_game_id, headers, cookies) {
  
  params = list(
    `gameId` = old_game_id,
    `justPlays` = 'false'
  )
  
  playlist_json <- httr::GET(
    url = 'https://nextgenstats.nfl.com/api/live/plays/playlist/game',
    query = params,
    httr::add_headers(.headers = headers),
    httr::set_cookies(.cookies = cookies)
  ) %>%
    httr::content(as='parsed')
  
  # get the names of every field that is used in the play-by-play
  # exclude the nest lists that contain play stats
  col_names <- playlist_json[['plays']] %>% 
    unlist %>% 
    names %>% 
    unique %>% 
    .[!grepl('playStats', .)]
  
  # get all the plays and make a df
  playlist_json[['plays']] %>%
    lapply(., function(x) unlist(x)[paste0(col_names)] %>% .[which(!is.na(.))]) %>% 
    dplyr::bind_rows() %>% 
    return()
}


ryoe_pbp_join <- function(nfl_pbp, ngs_pbp){
  pbp <- nfl_pbp %>% 
    filter(rush == 1,
           qb_scramble == 0,
           play_type != 'no_play',
           down <= 4,
           aborted_play == 0,
           !is.na(posteam)) %>% 
    mutate(posteam_type = if_else(posteam == home_team, 1, 0),
           home_team = nflreadr::clean_team_abbrs(home_team),
           away_team = nflreadr::clean_team_abbrs(away_team),
           roof = case_when(is.na(roof) & (home_team %in% c("ATL", "HOU", "IND")) ~ "dome",
                            TRUE ~ roof))
  
  cols <- c('old_game_id', 'play_id', 'posteam', 'drive_play_id_started', 'desc', 'play_type', 'game_id',
            'yards_gained', 'ydstogo', 'down', 'half_seconds_remaining', 'yardline_100',
            'roof', 'run_location', 'run_gap', 'wp', 'posteam_type',
            'offense.offenseFormation', 'offense.personnel', 'defense.defendersInTheBox',
            'defense.personnel', 'rusher_player_id')
  
  
  final_pbp <- pbp %>% 
    left_join(ngs_pbp,
              by = c("old_game_id" = "old_game_id",
                     "play_id" = "play_id")) %>% 
    select(all_of(cols))
  
  return(final_pbp)
  
}


ryoe_model_mutations <- function(joined_pbp, szn){
  
  rosters <- nflreadr::load_rosters(seasons = szn) %>% 
    select(gsis_id, position, season)
  
  pbp <- joined_pbp %>% 
    mutate(run_gap = case_when(run_location == "middle" ~ "middle",
                               TRUE ~ run_gap),
           season = as.numeric(substr(game_id, 1, 4))) %>% 
    filter(!is.na(run_location), !is.na(run_gap)) %>% 
    filter(!grepl('Punt formation', desc)) %>% 
    filter(!grepl('Field Goal formation', desc)) %>% 
    unique() %>% 
    left_join(rosters,
              by = c("season" = "season",
                     "rusher_player_id" = "gsis_id")) %>% 
    rename(rusher_pos = position)
  
  # roof, run_location, run_gap, offensive formation, offensive personnel, defensive personnel
  dummy_pbp <- pbp %>% 
    mutate(rusher_rb = if_else(rusher_pos == "RB", 1, 0),
           rusher_wr = if_else(rusher_pos == "WR", 1, 0),
           rusher_qb = if_else(rusher_pos == "QB", 1, 0),
           closed_roof = if_else(roof %in% c("closed", "dome"), 1, 0),
           # open_roof = if_else(roof %in% c("outdoors", "open"), 1, 0),
           rb_count = as.numeric(stri_sub(gsub(" RB.*$","",offense.personnel), -1)),
           wr_count = as.numeric(stri_sub(gsub(" WR.*$","",offense.personnel), -1)),
           te_count = as.numeric(stri_sub(gsub(" TE.*$","",offense.personnel), -1)),
           form_I = if_else(offense.offenseFormation == "I_FORM", 1, 0),
           form_empty = if_else(offense.offenseFormation == "EMPTY", 1, 0),
           form_jumbo = if_else(offense.offenseFormation == "JUMBO", 1, 0),
           form_pistol = if_else(offense.offenseFormation == "PISTOL", 1, 0),
           form_shotgun = if_else(offense.offenseFormation == "SHOTGUN", 1, 0),
           form_singleback = if_else(offense.offenseFormation == "SINGLEBACK", 1, 0),
           form_wildcat = if_else(offense.offenseFormation == "WILDCAT", 1, 0),
           # location_M = if_else(run_location == "middle", 1, 0),
           location_R = if_else(run_location == "right", 1, 0),
           location_L = if_else(run_location == "left", 1, 0),
           # gap_mid = if_else(run_gap == "middle", 1, 0),
           gap_end = if_else(run_gap == "end", 1, 0),
           gap_guard = if_else(run_gap == "guard", 1, 0),
           gap_tackle = if_else(run_gap == "tackle", 1, 0)) %>% 
    select(-c(rusher_pos,roof, offense.personnel, offense.offenseFormation,
              run_location, run_gap))
  
  model_cols <- c('season', 'game_id', 'posteam', 'play_id', 'drive_play_id_started', 'yards_gained',
                  'rusher_player_id', 'ydstogo', 'down', 'half_seconds_remaining',
                  'yardline_100', 'wp', 'posteam_type', 'defense.defendersInTheBox',
                  'rusher_rb', 'rusher_wr', 'rusher_qb', 'closed_roof',
                  'rb_count', 'wr_count', 'te_count', 'form_I', 'form_empty',
                  'form_jumbo', 'form_pistol', 'form_shotgun', 'form_singleback',
                  'form_wildcat', 'location_R', 'location_L', 'gap_end', 'gap_guard', 'gap_tackle')
  
  model_pbp <- dummy_pbp %>% 
    select(all_of(model_cols)) %>% 
    filter(!is.na(defense.defendersInTheBox),
           !is.na(rusher_rb))
  
  model_pbp[is.na(model_pbp)] <- 0
  
  return(model_pbp)
}


ryoe_model <- xgb.load("C:/Users/sphop/OneDrive/Betsperts/R/Fantasy-Evaluator/Code/RYOE.model")

add_ryoe <- function(nfl_pbp, ngs_pbp, szn) {

  
    orig_pbp <- ryoe_pbp_join(nfl_pbp = nfl_pbp, ngs_pbp = ngs_pbp)
    
    fin_pbp <- ryoe_model_mutations(orig_pbp, szn = szn)
    # for joining at the end
    
    # fin_pbp <- fin_pbp %>%
    #   dplyr::mutate(index = 1:dplyr::n())
    
    # prepare_xyac_data helper function shown below
    # passes <- prepare_xyac_data(pbp) %>%
    #   dplyr::filter(valid_pass == 1, distance_to_goal != 0)
    
    
    # fin_pbp
    rushes <- fin_pbp %>%
      # filter(season == 2021) %>% 
      dplyr::mutate(index = 1:dplyr::n())
    
      # user_message("Computing xyac...", "todo")
      
    join_data <- rushes %>%
      dplyr::mutate(index = 1:dplyr::n()) %>%
      dplyr::mutate(
        down = as.integer(down),
        ydstogo = as.integer(ydstogo),
        original_ydstogo = ydstogo
      ) %>%
      dplyr::select("index":"ydstogo", "original_ydstogo", dplyr::everything())
    

    preds <- stats::predict(
      ryoe_model,
      # get rid of the things not needed for prediction here
      as.matrix(rushes %>% select(-c(season, yards_gained, game_id, play_id, posteam,
                                     drive_play_id_started, rusher_player_id, index)))
    ) %>%
      tibble::as_tibble() %>%
      dplyr::rename(exp_ry = value) %>%
      dplyr::mutate(exp_ry = round(exp_ry, 4))%>%
      dplyr::bind_cols(
        tibble::tibble(
          "rushing_yds" = rep_len(-5:70, length.out = nrow(rushes) * 76),
          "index" = rep(rushes$index, times = rep_len(76, length.out = nrow(rushes)))
        ) %>%
          dplyr::left_join(join_data, by = "index")
      )

  return(preds)
}



# pbp <- nflfastR::load_pbp(seasons = 2017:2021) %>% 
#   select(-old_game_id) %>% 
#   filter(rush == 1,
#          qb_scramble == 0,
#          play_type != 'no_play',
#          # punt_attempt == 0,
#          down <= 4,
#          aborted_play == 0,
#          !is.na(posteam)) %>% 
#   mutate(posteam_type = if_else(posteam == home_team, 1, 0),
#          home_team = nflreadr::clean_team_abbrs(home_team),
#          away_team = nflreadr::clean_team_abbrs(away_team),
#          roof = case_when(is.na(roof) & (home_team %in% c("ATL", "HOU", "IND")) ~ "dome",
#                           TRUE ~ roof)) %>% 
#   left_join(schedule)
# 
# ryoe_model_mutations <- function(nfl_pbp, ngs_pbp) {
#   pbp %>%
#     dplyr::select(
#       'season', 'game_id', 'yards_gained', 'ydstogo', 'down', 'half_seconds_remaining',
#       'yardline_100', 'wp', 'posteam_type', 'defense.defendersInTheBox',
#       'rusher_rb', 'rusher_wr', 'rusher_qb', 'closed_roof',
#       'rb_count', 'wr_count', 'te_count', 'form_I', 'form_empty',
#       'form_jumbo', 'form_pistol', 'form_shotgun', 'form_singleback',
#       'form_wildcat', 'location_R', 'location_L', 'gap_end', 'gap_guard', 'gap_tackle'
#     )
# }